/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Model(props) {
  const Texture_Loader = new THREE.TextureLoader()
  const texture = Texture_Loader.load('/Model.png')
  const material = new THREE.MeshStandardMaterial( {map: texture} )
  texture.flipY = false
  const { nodes } = useGLTF('/Model.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0,-0.4,0.7]} scale={[0.3,0.3,0.3]} rotation={[0,-Math.PI * 0.1,0]}>
        <mesh geometry={nodes.Cube002.geometry} material={material} position={[0.02, 121.79, -159.38]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Model.gltf')
